@startuml
class Artiodactyl {
    + HoofCount : int <<get>> <<set>>
    + Artiodactyl()
    + Artiodactyl(hoofCount:int)
    + Artiodactyl(hoofCount:int, name:string)
    + Artiodactyl(hoofCount:int, name:string, speed:double)
    + Artiodactyl(hoofCount:int, name:string, speed:double, sleepTime:int, isSleep:bool)
    + Artiodactyl(name:string)
    + Artiodactyl(name:string, speed:double)
    + Artiodactyl(name:string, speed:double, sleepTime:int)
    + Artiodactyl(name:string, speed:double, sleepTime:int, isSleep:bool)
    + <<override>> Move() : void
    + <<override>> Print() : void
}
Mammalia <|-- Artiodactyl
@enduml
